name: UI Tests

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  web-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Run Tests
        run: mvn clean test -Dheadless=true

      - name: Generate Allure Report
        if: always()
        run: mvn allure:report

      - name: Upload Allure report artifact
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/allure-report

  deploy:
    needs: web-tests
    if: always()
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
